# Site settings
title: "亢龙无悔的博客"
description: "On the Way..."
baseurl: ""
url: "http://blog.wanghaiquan.cn"

plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 5

# Links
links:
  - title: "所有文章"
    url: /index
  - title: "标签"
    url: /tags
  - title: "关于我"
    url: /about
  - title: "订阅"
    url: /feed.xml
